### ISSUE TITLE
Add Speaker Priyadharshini, add abstract tiffany

### ISSUE THREAD

**Issue by sowmyaravidas** [aswinshenoy/shakticon#19]
Add speaker Priyadharshini from AMI. 
Confirmed time: 11th April 15:00-16:00 IST.
speaker bio + photo in google form.

Tiffany updated her abstract. Add this to website if not done already

**Comment by tssavita** [comment]
done

**Comment by sowmyaravidas** [comment]
Additional comments received from speaker Priyadharshini. Please edit accordingly:

----------------------

In my speaker description – the company name is mentioned as “America Megatrends International LLC” – It should be “American Megatrends International LLC”

And the title of the session can also be modified as “Firmware Security – An Introduction”
