### ISSUE TITLE
Add new speakers

### ISSUE THREAD

**Issue by spchal** [aswinshenoy/shakticon#2]
Three additional confirmed speakers to be added. Details are in the form response: 
1. Asha Poluru : Talk Detail in form, pic in mail forwarded to Savita
2. Priti Shrivastav : Talk Detail in form, pic forwarded to Savita - she sent two. take the latest pic. 
3. Yarden Shafir: Training Details in form. Pic might be a little late. But, info can be added without picture.

**Comment by tssavita** [comment]
1. Added to landing page. To add to /speakers, need more info about the speaker. 
2. Priti S has been added.

**Comment by AshwAthi8** [comment]
Add to /speakers
- [x]  Sreelakshmi Panangatt (details in the form)

**Comment by tssavita** [comment]
Have added all speakers/trainers to landing page and all except Asha P to /speakers and /trainers respectively. Closing this for now. When we have more information about Asha P you could reopen this issue.
