### ISSUE TITLE
Add preconference Talk crowdstrike

### ISSUE THREAD

**Issue by sowmyaravidas** [aswinshenoy/shakticon#27]
CrowdStrike Talks

Jhilmil Kochar, Managing Director, CrowdStrike, Pune India

     Slot - 02-Apr-21  Time: 20.00 hrs (IST)
      Talk Title - Cybersecurity for IOT/ICS
       Photo: https://drive.google.com/file/d/10ZyO0EJPTvufQIiXqwFeyJ09oRbH05gU/view?usp=sharing

 Abstract 
 
In this talk, you will learn about the challenges faced around cybersecurity in IOT, with special focus on ICS environment. The talk will also cover recent trends in the threat landscape and a wholistic approach towards a more secure manufacturing environment.

      Bio
Jhilmil has been serving as the Managing Director, CrowdStrike India for the past 4 years. She set up the India team from scratch and has been delivering security products for IT security operations. She comes armed with 25+ years of technology leadership experience in domains spanning Cybersecurity, Telecom and Networking, Semiconductor and IOT, Gaming and Multimedia. Earlier she led the India center for WMS Gaming, a Scientific Games company. Prior to that she has worked as in various engineering leadership roles at McAfee and Conexant Systems.

**Comment by tssavita** [comment]
done, please review: https://shakticon.com/speakers and https://shakticon.com.

**Comment by sowmyaravidas** [comment]
Please add Pune India in the affiliation of the speaker @tssavita
