### ISSUE TITLE
Add speaker for April 10th CrowdStrike

### ISSUE THREAD

**Issue by sowmyaravidas** [aswinshenoy/shakticon#28]
Komal Armarkar, Security Analyst

     Slot -10-Apr-21  Time: 15.00 hrs (IST)

     Talk Title - Recon to Software Supply Chain Attack

     Photo: https://drive.google.com/file/d/1dtVPceLxaTOB_JXfSGCvtreWXiRl3EKl/view?usp=sharing

     Abstract:

 "As our society is becoming more and more technologically reliant, the importance of cybersecurity is on rise. A single cyber-attack can cause heavy damages to businesses. Organisations today face unprecedented number of attacks that begin even before any software is ever made. Supply chain attacks can damage organisations, individual departments, or entire industries by targeting and attacking insecure elements of the software supply chain. A software supply chain attack infiltrates software life cycle by leveraging open source components to inject malicious code in order to compromise software systems further down the chain.

The presentation will discuss how simple recon techniques like JavaScript recon, GitHub recon, social engineering can lead to highly damaging software supply chain attacks and measures to protect against them.

The target audience for this talk would be anybody who is currently working or who has just started in cyber security field or anybody who wants to learn something new.

    Bio:

Komal Armarkar is currently working as Security Analyst in Spotlight vulnerability management team at CrowdStrike. In her overall experience of 7 years, she has worked in various fields like policy compliance, Linux system administration and application security. She has a keen interest in vulnerability analysis and research, application security.

**Comment by tssavita** [comment]
Done
