### ISSUE TITLE
Add Speaker for 11th April CrowdStrike

### ISSUE THREAD

**Issue by sowmyaravidas** [aswinshenoy/shakticon#29]
Aarti Gupta, Director Engineering

     Slot - 11-Apr-21 Time: 16:00 hrs (IST)
     
     Talk Title - Security at Cloud Scale

     Photo: https://drive.google.com/file/d/1ZhyF5Kel3v2lzR5YuASEWFrKEkviT09p/view?usp=sharing

Abstract  

In this talk, Aarti looks at the evolution of EDR technology over the years and how the cloud has been leveraged to improve upon the fidelity of traditional EDR systems.

 Bio

Aarti is a Director of Engineering at CrowdStrike, she is currently working on a next-gen cloud-based security product. Previously, she was Director of Engineering at Qualys and was responsible for building out Qualys’s Security Analytics platform. Aarti has extensive experience with building web scale systems, having previously worked for Amazon and Hotstar

**Comment by tssavita** [comment]
Done
